### ISSUE TITLE
Make API for raw data consumption

### ISSUE THREAD

**Issue by kosamari** [kosamari/who-pays-tech-speakers#10]
Dataset is getting more than 200, for implementing #2  & better data distribution, I'd like to add API.

Current setup is using MongoDB and fetch all data as JSON, send it to client. 
Perhaps just switch to CouchDB and expose the read interface?

**Comment by montogeek** [comment]
Hi @kosamari 
If nobody else is participating, I will start working on it.

**Comment by kosamari** [comment]
@montogeek don' think anyone is woking on it. So take it away!

**Comment by kosamari** [comment]
As I think more about it, what this API needs first is ability to page through few data set at a time. 
so like  `/api/reports` returns

```
{
  length: 230, <= total dataset length
  next: '/path-to-next-dataset'
  prec:'/path-to-prev-dataset'
  data : [
  // first 50 reports file in array
 ]
}
```

or something. 
OR use Link header like Github API does?

I have no opinion / experience on this, so if you have idea just take it away however you like :)
All I know is data is better represented in whole report set, I don't think filtering is a top priority.

**Comment by kosamari** [comment]
Now that I think about it, I think basic needs for data pagination is filled with @alexbooker 's PR  #24 :)

**Comment by montogeek** [comment]
Do you want to create endpoints to create, update or delete a report?

**Comment by kosamari** [comment]
ah this will be **read only** api. 
Things I can think of is a filter data by certain metrics?

**Comment by kosamari** [comment]
there is http://whopays.techspeakers.info/data.json that should serve purpose.
