### ISSUE TITLE
Suggestion: collect data for speaking opportunities declined due to costs/pay considerations

### ISSUE THREAD

**Issue by cczona** [kosamari/who-pays-tech-speakers#16]
Sometimes a speaker has to say no, or reluctantly decides not to propose, because of financial considerations such as the ones this project inversely highlights. The taboo of asking organizers about money is a compounded by unease about disclosing one's financial status to a conference organizer. So gathering this data would be beneficial for shining light on how proposal pools and finalized schedule are being quietly affected. 

Ability to cover travel costs, and need for compensation, are particularly a factor for marginalized people. For example:
- _Pay Gap_: On average, women and most people of color have [less pay (even in tech)](http://www.usatoday.com/story/tech/2014/10/09/high-tech-pay-gap-hispanics-asians-african-americans/16606121/).
- _Wealth Gap_: On average, most peoples of color [less savings](http://www.washingtonpost.com/news/get-there/wp/2015/02/18/the-racial-wealth-gap-we-hardly-talk-about-what-happens-in-retirement/) (final paragraph), [less household wealth](http://money.cnn.com/2015/02/18/news/economy/wealth-blacks-whites-hispanics/)
- _Household Costs_: Blacks and latinas/latinas/hispanics) [carry greater burden of insurance costs](http://www.forbes.com/sites/laurashin/2015/03/26/the-racial-wealth-gap-why-a-typical-white-household-has-16-times-the-wealth-of-a-black-one/).
- _Caregiving_: Working women [bear more childcare responsibilities](http://www.pewresearch.org/fact-tank/2015/03/10/women-still-bear-heavier-load-than-men-balancing-work-family/). Single mothers must deal bear [expensive childcare costs]()while away at a conference. (Unfortunately this study on [costs to employed single mothers](http://www.jstor.org/stable/42955741?seq=1#page_scan_tab_contents) is behind a paywall.)
- _Age Gap_: Once [women are older than 25, age increases the pay gap](http://www.businessinsider.com/gender-pay-gap-rates-by-age-2015-1)
- _Trans Discrimination_: Transpeople are highly likely to have [an array of significant financial obstacles](http://www.pri.org/stories/2015-04-18/why-we-cant-forget-transgender-people-when-talking-about-pay-gap)

**Comment by kosamari** [comment]
Thanks @cczona ! 
So I spent quite sometime thinking about this before releasing the site & decided to go with "who pays" not "who didn't pay". As much as this project came out of frustration around how conference handles travel and accommodation, I wanted to as equally showcase which conference has been great at treating speakers.

I believe this issue of "I could not/ declined to speak" should be addressed somewhere but not on this particular form. I think @remy 's article & comments on that article has lots of thoughts already. https://remysharp.com/2014/03/07/youre-paying-to-speak 

So,  I'm not adding this particular angle to whopays.techspeakers.info
1. I'm leaving this issue open for discussion, if anyone want to share "I did not speak because X",  welcome to leave comment :)
2. If anyone want to make similar form like "whopays" happy to assist on making site (provide hosting server / host under same techspeakers.info domain if you like)

**Comment by cczona** [comment]
> decided to go with "who pays" not "who didn't pay"

"Who didn't pay" is directly addressed by the form.

![image](https://cloud.githubusercontent.com/assets/709364/10843072/ace84af2-7eb3-11e5-8d31-40f0d657fec8.png)

![image](https://cloud.githubusercontent.com/assets/709364/10843027/6b4a8e8e-7eb3-11e5-95fe-b807966e83e6.png)

"Who didn't pay" data is in the generated summaries too. Such as in these excerpts from examples which are currently 2nd and 3rd on the homepage.

> "I was not paid to speak. The event did not pay for my travel and accommodation. My employer did not pay my travel expenses, and I used my PTO to speak."

and

> "The event did not pay for my travel and accommodation. My employer paid some of my travel expenses, and I used my PTO to speak."

![image](https://cloud.githubusercontent.com/assets/709364/10842929/ccf4f38c-7eb2-11e5-8dcd-b70a50d4beaf.png)

Being more concrete about describing one potential approach:
1. _Between 1st and 2nd row, insert "I `(did | did not)` speak. Cost was `(unimportant | somewhat important | very important | pivotally important)` factor for that decision._
2. _If `"did not"` gets selected, toggle some verbs (mostly just "was" to "would have")_ on the remainder of the form.

It's neutral wording that covers a wide range of scenarios, e.g.
- Person did not propose, or declined invite to speak, because of anticipated cost
- Speaker withdrew their talk because of change of financial conditions (e.g. airfare increase, or exchange rate change, or job loss, or difficulty finding a sponsor)
- Employer asked speaker to withdraw because of a shift in the company's budget priorities
- Conference reduced the amount of funding available for covering speakers
- Conference withdrew funding due to last-minute loss of sponsor or a large unbudgeted expense

Summary: "impact" is added to "who does pay" and "who doesn't pay"

**Comment by cczona** [comment]
I should note that it also covers the inverse of most of those scenarios: person was motivated to propose/accepted/speak because of funding

**Comment by kosamari** [comment]
@cczona thanks for the input.
I should also note this form is collecting voice from who spoke - who accepted & put time into travel and making talk, and how they were compensated. 

As I said in previous comment, I'd like to keep the scope same but open to collaborating in other way.
