### ISSUE TITLE
Pagination for "show all"

### ISSUE THREAD

**Issue by kosamari** [kosamari/who-pays-tech-speakers#2]
currently client app downloads entire database records and display. Probably needs pagination at somepoint.

**Comment by bookercodes** [comment]
Would you like me to create an end-point with pagination parameters...? (implementation for #10)

I could then add a  _"load more"_ button _or_ page numbers to the UI. (implementation for this issue.)

**Comment by kosamari** [comment]
@alexbooker I think keep hitting load more (twitter style) would be nice :)

**Comment by bookercodes** [comment]
@kosamari Good morning. 

I'll get on this now.

**Comment by kosamari** [comment]
@alexbooker thanks for PR ! just merged the server side code :)

**Comment by bookercodes** [comment]
Awesome :smile:. 

I'll get on the front-end part shortly.

**Comment by bookercodes** [comment]
Closed by #24 and #32 :smiley:
