### ISSUE TITLE
Opting out of conference payments

### ISSUE THREAD

**Issue by dshafik** [kosamari/who-pays-tech-speakers#27]
Some companies do not allow employees to accept honorariums while "on the clock" (meaning, we'd have to take vacation time for the event), and for similar reasons some people do not accept travel/accommodation from the event, instead having their company pay for it (e.g. Dev Evangelists).

Perhaps something like:

"The conference **_1**_ to cover my ____2____ costs." where **_1**_ is "offered", "did not offer", or "was unable" and **_2_**_ is "accommodation", "travel", or "travel and accommodation". This also might help with conferences that have an "ask us if you need help" policy, but do not generally cover costs.

Not sure if this can be handled well, it's not the general case, but I also don't want to negatively reflect on the many conferences who do offer travel/accommodation (it's pretty standard in the PHP community, though honorariums are not) that I choose not to take advantage of.

**Comment by kosamari** [comment]
@dshafik thank you for input.
Yeah I'm finding it difficult to fill all type of scenario to this "story telling" format.
In short, my basic thinking when making the form was tell story from individual's point of view & keep it minimal "what I got from who" narrative. 

So I'd like to keep the form as is but open to editing tool tip or notes section to guide an one-off story people want to add to "Also:" section.
for example, `if you were offered honorarium, but declined, you can leave this empty & tell us more at Also:`  or something.

Do you have any suggestion?

So far I am finding, naturally, if the speaker had good time at conference & care about conference, they do put clarification on their particular scenario in Also: section.
