### ISSUE TITLE
Volatile db.init Function

### ISSUE THREAD

**Issue by bookercodes** [kosamari/who-pays-tech-speakers#33]
On [this line](https://github.com/kosamari/who-pays-tech-speakers/blob/master/app.js#L9) you import `db`:

``` js
var db = require('./db').init();
```

`init` returns immediately despite calling asynchronous functions internally. 

In practice, this means that if a `db` function is called before the `db` has finished initializing, an _"undefined is not a function"_-type error will occur.

Imagine you run the server and then quickly go to `/reports/page/1`. `db` _may_ not yet be initialized which will subject the `/reports/page/1` middleware to an error.
### Possible Solutions
- Make `init` synchronous by calling synchronous functions on the Mongo client (assuming there are any).
- Make `init` call it's `cb` argument. Call `server.start` from the `cb`.

**Comment by kosamari** [comment]
YES ! I just discovered this last night ( https://twitter.com/kosamari/status/659888069865316352 )

**Comment by kosamari** [comment]
closing this - moved database to firebase
