### ISSUE TITLE
Correct Frontend Conf Zurich comment about profitability

### ISSUE THREAD

**Issue by matthiasmoier** [kosamari/who-pays-tech-speakers#35]
[This entry](http://whopays.techspeakers.info/56308a8ded1477f70cc477f9) mentions Frontend Conference Zurich as a `for profit` event

Frontend Conf Zurich is a public, not-for-profit event. We see our conference as a community event and a great opportunity to meet and learn from brilliant people. That’s why we try to keep ticket prices a low as possible to make an event that is affordable for everyone. (Which is not too easy in one of the most expensive cities in the world.)

All the money we get is used to pay for the event expenses (e.g. travel and accommodation of our speakers, speakers honorarium, free food and snacks for our attendees, etc.) and as a basis for our next event. We're a team of web professionals that [organizes these events in our spare _(and unpaid)_ time](https://frontendconf.ch/about/#organization).

**Comment by bookercodes** [comment]
It [_is_](https://github.com/kosamari/who-pays-tech-speakers/issues/25) possible to correct entries but the process is manual. @kosamari is travelling at the moment but I'm sure she'll get on this as soon as she has time!

**Comment by kosamari** [comment]
@matthiasmeier thanks for input & @alexbooker thanks for issue tracking !
Just updated database :)

**Comment by matthiasmoier** [comment]
Thank **you** for the website and the correction.
