### ISSUE TITLE
Show More Reports per Page

### ISSUE THREAD

**Issue by bookercodes** [kosamari/who-pays-tech-speakers#36]
At the moment, only one report is shown per page:

![](https://i.imgur.com/Wr50eWz.png)

It would be better to show more posts - 5 per page is probably sensible.

The number of posts to render per page is defined [_here_](https://github.com/kosamari/who-pays-tech-speakers/blob/master/db.js#L26).

**Comment by kosamari** [comment]
just fixed it to load 5 each.

**Comment by bookercodes** [comment]
Nice one.
