### ISSUE TITLE
correct devopsdays chicago entry about ignite speaker being charged

### ISSUE THREAD

**Issue by mattstratton** [kosamari/who-pays-tech-speakers#38]
[This entry](http://whopays.techspeakers.info/565497c037c07782378fabcb) says that the speaker was asked to pay a full price ticket for speaking as an Ignite speaker at DevOpsDays Chicago.

DevOpsDays Chicago provides free tickets to all speakers (30 minute talks and Ignites both). As well, we checked our records, and the one person who we provided travel assistance for who was international has confirmed with me that he is not the one who posted this. There has not been an Ignite speaker at DevOpsDays Chicago who was provided travel assistance internationally and was asked to pay their own admission to the event.

**Comment by kosamari** [comment]
Just updated, sorry for delay !
