### ISSUE TITLE
ChefConf does not charge speakers

### ISSUE THREAD

**Issue by nathenharvey** [kosamari/who-pays-tech-speakers#39]
[This entry](http://whopays.techspeakers.info/5630f9cde41c96231ee3bf73) says that the speaker was asked to pay a full price ticket for speaking at ChefConf in San Francisco.  It also states that the conference is not for profit.  

ChefConf has always provided free passes for all speakers.  ChefConf is organized and run by Chef Software, Inc., a for profit company.  I have been the chairman of the conference since 2013 and can provide further details if required.

**Comment by kosamari** [comment]
Updated, Thanks !
