### ISSUE TITLE
Add validation of empty fields

### ISSUE THREAD

**Issue by colabug** [kosamari/who-pays-tech-speakers#4]
I don't know what is the right number of required fields, but I accidentally hit "Enter" when I was selecting something from a drop down and prematurely submitted.

Ended up with only: "I was invited to speak at DroidCon London in London."

**Comment by bookercodes** [comment]
I'm not sure how this would work as _"All fields are **optional** & All submissions are anonymous."_

A confirmation dialog could work:

![](http://guides.rubyonrails.org/v4.0.4/images/getting_started/confirm_dialog.png)

**Comment by kosamari** [comment]
@colabug @alexbooker thanks for suggestion ! 
Yes, at the moment, if you have at least 1 field filled, you can submit form.

When I was initially making this, I thought of confirmation modal...but made UX decision to go with simpler & casual way to submit. (same reason why form is very limiting, didn't want to make it 2 page scroll lists.)

Perhaps the way around is filtering those what look like a mistake submission (i.e "I was ___ to ___" ) in results report.

**Comment by cczona** [comment]
I agree with the intent to keep everything optional. Of course, unintentionally incomplete submissions have its own problems. Maybe a non-blocking validation of field count? e.g.

"You've filled in__ fields. All fields are optional, so it's cool to do that if you'd like. Okay to submit as-is?"

**Comment by kosamari** [comment]
ah! just had an idea. I'm going to add validation & don't allow to submit unless it was 
- click
- hit enter while submit button is in focus (for accessibility)
