### ISSUE TITLE
Non-jargon way of saying "CFP"

### ISSUE THREAD

**Issue by kosamari** [kosamari/who-pays-tech-speakers#8]
The form has " I was selected from CFP " I'd like to change that to something more clear.

My original thought to call this as CFP was, some conf use this as "call for **proposal** " or "call for **paper**" (both intended for talk submission).

Thinking more about it, even "call for proposal/paper" is a odd word if you never looked at how speakers for conference gets selected.  Any suggestion?

**Comment by noopkat** [comment]
perhaps " I was selected after submitting a talk proposal" ?

**Comment by lewiscowper** [comment]
How about, "I submitted a talk", because the alternatives are around being invited vs being a sponsor.

There's an implicit "and it was accepted" because you start off with "I spoke at ______ conference, and ...".

**Comment by noopkat** [comment]
@lewiscowper I like Lewis' :clap:

**Comment by mkivikoski** [comment]
+1 for @lewiscowper suggestion.

**Comment by brianloveswords** [comment]
Playing off @lewiscowper's good suggestion, maybe even "I submitted _an idea for_ a talk"

**Comment by lewiscowper** [comment]
I like @brianloveswords' addition, rounds it out, and I know (at least from my experience) that we often don't have the talk already written when we fire off an abstract.

**Comment by ajpiano** [comment]
"Call For Speakers" is usually what I call it from "what's on the web site" standpoint.

**Comment by kosamari** [comment]
Thanks everyone for suggestion! 
I think going with  @brianloveswords and @lewiscowper 's suggestion and use "I submitted an idea for a talk" would fit well. This also eliminates "I was selected" word which feels a little bit like speaking is "a club" 

<3 you all for the help !

**Comment by kosamari** [comment]
hey @brianloveswords @lewiscowper 
this might be silly question but which sounds better ?

"I submitted an idea"
"I proposed an idea"

Came to realize proposed is better for seasoned speakers who knows what CFP is...? I'm wondering if the form says "submitted" people who used calling this CFP would thing "what do you mean by submitted?"

**Comment by lewiscowper** [comment]
Proposing an idea is better IMO, because you lack the knowledge of where
it's being submitted to, so propose sounds more like it was speculative
